

item={
    "single rice": 1,
    "M&M":2,
    "egg":3,
    "lego brick" :4,
    "baby bottle":5,
    "plastic fork": 6,
    "sponge": 7,
    "rubber duck": 8,
    "dvd disc" : 9,
    "cookie": 10,
    "soap": 11,
    "fish": 12,
    "toothpaste": 13,
    "trash bag" : 14,
    "fan": 15,
    "box": 16,
    "soccer ball": 17,
    "teddy bear": 18,
    "frying pan": 19,
    "headphones": 20,
    "xbox one": 21,
    "ps5":22,
    "gaming pc": 23,
    "toaster": 24,
    "bed": 25,
    "drill": 26,
    "microwave": 27,
    "toilet": 28,
    "shopping cart": 29,
    "bathtub": 30,
    "car": 31,
    "truck": 32,
    "airplane": 33,
    "monster truck": 34,
    "dump truck": 35,
    "tree" : 36,
    "moon": 37,
    "eiffel tower": 38,
    "nuke": 39,
    "godzilla": 40
}