

item={
    "egg":1,
    "baby bottle":2,
    "plastic fork": 3,
    "sponge": 4,
    "rubber duck": 5,
    "cookie": 6,
    "soap": 7,
    "fish": 8,
    "toothpaste": 9,
    "trash bag" : 10,
    "fan": 11,
    "box": 12,
    "soccer ball": 13,
    "teddy bear": 14,
    "frying pan": 15,
    "headphones": 16,
    "xbox one": 17,
    "ps5": 18,
    "gaming pc": 19,
    "toaster": 20,
    "bed": 21,
    "drill": 22,
    "microwave": 23,
    "toilet": 24,
    "shopping cart": 25,
    "bathtub": 26,
    "car": 27,
    "truck": 28,
    "plane": 29,
    "monster truck": 30,
    "dump truck": 31,
    "nuke": 39,
    "godzilla": 40
}
